version: 2

sources:
  - name: staging
    database: dbt-module-4-28646 #project
    schema: trips_data_all #dataset

    tables:
      - name: new_yellow_tripdata
      - name: new_green_tripdata